name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

  deploy:
    runs-on: ubuntu-latest
    needs: [laravel-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Deploy to Server
        env:
          SERVER_USER: wicaksu
          SERVER_IP: 103.132.230.115
          SERVER_PASSWORD: Jack03061997
          DEPLOY_PATH: /home/wicaksu/spbe
        run: |
          expect <<EOF
          spawn ssh wicaksu@103.132.230.115
          expect "password:"
          send "Jack03061997\r"
          expect "$ "
          send "cd /home/wicaksu/SPBE && git pull origin main && composer install --prefer-dist --no-progress --no-suggest && php artisan migrate --force && php artisan optimize\r./vendor/bin/sail down\r./vendor/bin/sail up -d\r"
          expect "$ "
          send "exit\r"
          expect eof
          EOF
