name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute deployment script via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 103.132.230.115
          username: wicaksu
          password: Jack03061997
          script: |
            cd /home/wicaksu/SPBE
            ./vendor/bin/sail down
            git pull origin master
            composer install
            ./vendor/bin/sail up -d
