name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder for Laravel Tests
        run: echo "Running Laravel tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Deploy to Server
        env:
          SERVER_USER: wicaksu
          SERVER_IP: 103.132.230.115
          SERVER_PASSWORD: Jack03061997
          DEPLOY_PATH: /home/wicaksu/spbe
        run: |
          expect <<EOF
          spawn ssh $SERVER_USER@$SERVER_IP
          expect "password:"
          send "$SERVER_PASSWORD\r"
          expect "$ "
          send "cd $DEPLOY_PATH && git pull origin main && composer install --prefer-dist --no-progress --no-suggest && php artisan migrate --force && php artisan optimize\r"
          send "./vendor/bin/sail down\r"
          send "./vendor/bin/sail up -d\r"
          expect "$ "
          send "exit\r"
          expect eof
          EOF
